### ISSUE TITLE
Text style in recommended recipe page and saved recipe page

### ISSUE THREAD

**Issue by DontWorry33** [jason741852/project276#10]
The text being underlined and spaced makes it look a bit funny. It looks like there are underscores in the beginning of the names. Should just underline the actual text and not the empty space before or after it. Attached an image because its a little hard to explain.

[text style](http://i.imgur.com/0kGA8Jd.png)

**Comment by afkewolczyk** [comment]
Fixed the underlining by adding a new column to the table. Did this in both favourite recipes and recommended recipes.

**Comment by DontWorry33** [comment]
Looks a lot better. Am closing this for now!
