### ISSUE TITLE
Admin page(s) needs to be created

### ISSUE THREAD

**Issue by DontWorry33** [jason741852/project276#13]
A requirement for our first iteration is that we have multiple types of users that can log in and have specific pages. We talked about this briefly, so to summarize, an admin should:

- Be able to create, look at, update and delete any user
- Be able to modify a users role
- Be able to modify a users saved recipes and preferences

**Comment by DontWorry33** [comment]
Forgot to reference this issue in a few commits. The following below all relate to this issue
2629c9dfe8ac3fc14a8b4513f4ffa154549b82d7
91545f979d4b9b0d38c1d9a2445845bce349bb3f
eb8e80f7f0b5b8d9dfba80109ee63d5ba7448850

**Comment by afkewolczyk** [comment]
I created a user with role = 2 and trued to navigate to /users but am unable to find the admin view

**Comment by afkewolczyk** [comment]
Found it! Works
