### ISSUE TITLE
User password gets modified upon preference update on recommended recipe page

### ISSUE THREAD

**Issue by DontWorry33** [jason741852/project276#14]
So I found an interesting bug right now. If you update your preference on the recommended recipe page and click save, then log out, you will not be able to log in again with the same password.

I have a theory to why this happens. When we call the preference to save, it has to update the preference and since the preference has a relationship with the user, I think it also saves the user model. This means that the encrypt_password function is called (as it should be whenever the user is saved) and the salt/password is updated. 

So for now, I would suggest to fix this bug, we remove updating preferences from the recommended recipe page for the following reasons:

1) It will fix this bug
2) In terms of flow, a user technically shouldn't be able to modify their preferences without going into their settings anyways and confirming their password (or entering a new one).
3) This lets us have exactly one area dedicated to the user preferences

This is mostly just my opinion. Please respond with yours and if you agree or disagree. If no one responds before the deadline, I will just remove it.

**Comment by afkewolczyk** [comment]
I say just remove it for now, not being able to log in is a bigger issue.

**Comment by DontWorry33** [comment]
fixed in 74873c3fec443a8f2cf225a050f0e7004b93a2f8
