### ISSUE TITLE
Add the share featre

### ISSUE THREAD

**Issue by afkewolczyk** [jason741852/project276#26]
Share by: email, facebook, twitter?, google?

**Comment by jason741852** [comment]
added facebook sharing feature. Needs further testing a12186d

**Comment by DontWorry33** [comment]
looks good so far. we can test with heroku and if it works we will close!

**Comment by jason741852** [comment]
added twitter sharing. Again will need further testing on heroku.

**Comment by afkewolczyk** [comment]
looks good!
