### ISSUE TITLE
No results found for certain combinations

### ISSUE THREAD

**Issue by DontWorry33** [jason741852/project276#3]
I tested this by creating an account and using egg-free with low-carb and it said: No results found for search criteria Diet=low-carb & Health=egg-free

This is however incorrect because when I queried the API with the following link: 

https://api.edamam.com/search?app_id=ed2714cc&app_key=81029d1bb3daad9d1bdaf4a46adca6b2&q=&diet=low-carb

I retrieved results, 7 of which fit both the criteria....

This needs to be fixed ASAP

**Comment by mehrshad9821** [comment]
fixed
