### ISSUE TITLE
Show error message if no results match their dietary restrictions

### ISSUE THREAD

**Issue by afkewolczyk** [jason741852/project276#30]
right now, if you search something and nothing matches, or if you enter diet labels and nothing matches, it just shows a blank page. should show "try searching again, nothing matches" or something like that!

**Comment by afkewolczyk** [comment]
Fix in  732345c in my branch afke_itr3 (will merge soon)

**Comment by DontWorry33** [comment]
Works great! good job labeling the recommended recipes message message and the search message differently.
