### ISSUE TITLE
Add "forgot your password" feature

### ISSUE THREAD

**Issue by afkewolczyk** [jason741852/project276#32]
Use a mailer to reset password? 
http://railscasts.com/episodes/274-remember-me-reset-password
http://eileencodes.com/posts/adding-additional-functionality-to-forgot-your-password/

**Comment by DontWorry33** [comment]
You had it all but just needed to define the SMTP settings. I tested it with one of my personal accounts and it seemed to work great! To test it, edit the configuration in:

config/application.rb

with your personal information (do not commit it though!)

**Comment by afkewolczyk** [comment]
Thanks so much hussain, i was stuck on that for hours!!
