### ISSUE TITLE
create better seed for usability

### ISSUE THREAD

**Issue by jason741852** [jason741852/project276#38]
create user seed so we don't need to sign up users every time we drop db

**Comment by afkewolczyk** [comment]
I was trying to figure out how to use this gem: https://github.com/vigetlabs/sprig-reap and will let you know if i figure it out, it does automatic seeding of whats in a database. 
having troubles seeding users with hashed passwords.

**Comment by afkewolczyk** [comment]
My only other idea is we create the app, create a bunch of users, and then in the seed file we can add the favorite recipes and comments, etc. So create users before we seed. Not sure if that'll work.

**Comment by DontWorry33** [comment]
I'm going to try creating the user seeds and the voting seeds (to showcase that part) tomorrow.

**Comment by jason741852** [comment]
see issue #24. I was having a hard time to come up with the query for the vote or highest saved because I couldn't find the db mockup. Also I feel like it would have been a bit easier if we separated vote and comment into 2 models.

**Comment by DontWorry33** [comment]
db mockup is https://github.com/jason741852/project276/blob/master/db/schemamockup/db-mockup-itr2.png

**Comment by jason741852** [comment]
thanks!

**Comment by DontWorry33** [comment]
Alright we came up with a good solution to this! Thanks guys
