### ISSUE TITLE
Cant show image when loading the reccomended recipes, and then they load

### ISSUE THREAD

**Issue by afkewolczyk** [jason741852/project276#41]
@DontWorry33 I think you mentioned that you added a loading bar or something for when the recipes are loading. I tried this in both safari and google chrome on my mac, im not usre if its just because im on a mac but this always pops up. 
<img width="647" alt="screen shot 2016-12-02 at 9 26 54 pm" src="https://cloud.githubusercontent.com/assets/22460540/20857071/38306da8-b8d6-11e6-9de5-f922ed63dad3.png">

And then the rest load up nicely!

**Comment by DontWorry33** [comment]
Oops! I forgot to commit the image. I'll do it right now

**Comment by DontWorry33** [comment]
Sorry about that, done.

**Comment by afkewolczyk** [comment]
The gif looks great.
