### ISSUE TITLE
passing r["url"] to onclick function in search

### ISSUE THREAD

**Issue by jason741852** [jason741852/project276#43]
5344753 not sure how to put the double quotes here as the console keeps giving me different errors. Otherwise the function call should work properly

**Comment by DontWorry33** [comment]
Here's how I did it in recommended recipes:

 onclick="save_recipes($(this),'+"'"+r['uri']+"'"+')"

**Comment by jason741852** [comment]
yeah I saw that so I tried this last night. Maybe I interpreted this wrong but to confirm is this equals to ''"r['uri']"'          ?

**Comment by DontWorry33** [comment]
In the javascript it's equivalent to the url encased by ' ' so if the url was google it'd give you 'www.google.com'

**Comment by jason741852** [comment]
url is passing now but I'm getting an error "undefined method 'join' for nil:class" in user controller. I guess you have encountered this before when you were writing the save_recipe method?

**Comment by DontWorry33** [comment]
Fixed during merges! Closing
