### ISSUE TITLE
Popular recipe of week 

### ISSUE THREAD

**Issue by afkewolczyk** [jason741852/project276#46]
Popular recipe of week does not work on heroku if you are not logged in 
(I just clicked it and it says page does not exist)

**Comment by jason741852** [comment]
that's because non-users are not allowed to store anything into database (clicking thumbnail will automatically put recipes into database in order to render recipe/show ). But I thought @DontWorry33 pushed a fix already?

**Comment by DontWorry33** [comment]
Oh sorry I forgot to push it. Doing now
