### ISSUE TITLE
Tests are failing/broken

### ISSUE THREAD

**Issue by DontWorry33** [jason741852/project276#5]
Try running rake test:models and rake test:controllers on the Control branch. There are errors and failures in the tests.

Please run this before committing and make sure that everything passes

**Comment by khashiyousefi** [comment]
hey guys, we have created spec file for new tests and some other modifications. you can run command => rspec spec 
unfortunately, we forgot to use the most updated files, thats why i pushed everything to the Controller.

**Comment by DontWorry33** [comment]
Doesn't run for me. Keeping the issue open for now
![screenshot from 2016-11-14 16-11-44](https://cloud.githubusercontent.com/assets/1332609/20287985/ebe6dc2a-aa84-11e6-98bd-e9e1b33c444f.png)

**Comment by khashiyousefi** [comment]
let me push everything one more time

**Comment by khashiyousefi** [comment]
try one more time hopefully it works this time

**Comment by DontWorry33** [comment]
Nope, same error. 
![screenshot from 2016-11-14 16-21-35](https://cloud.githubusercontent.com/assets/1332609/20288171/4b967198-aa86-11e6-94a4-02df3becce15.png)

**Comment by DontWorry33** [comment]
I updated the tests for itr3, removed the old ones and added some new ones for integration/controller in ef5a307

**Comment by afkewolczyk** [comment]
fixed!
