### ISSUE TITLE
Preferences update but recommended recipes do not change on update

### ISSUE THREAD

**Issue by DontWorry33** [jason741852/project276#6]
No matter what I put in my healthlabel I always get the same generated recipes.. this is incorrect as even if I put dairy-free, I am getting results that contain dairy. These recommended recipes never get updated when I change my health label (which they should). It does however work when I update the dietlabel.

**Comment by mehrshad9821** [comment]
API doesn’t render results like mentioned in issue description.. You can check by browser url
!!!
