### ISSUE TITLE
Saved recipes are not reflected in the recommended list after refresh

### ISSUE THREAD

**Issue by DontWorry33** [jason741852/project276#7]
After saving a recipe and refreshing the page, the recipe still shows as "Save recipe" until you click it, then it says already saved.

This is not quite correct as it should either:
a) Not show in the recommended recipes anymore as it's already saved
b) Show "Saved" without the user having to click "Save Recipe" again

If you guys come up with better ideas to reflect this, that's also great.

**Comment by afkewolczyk** [comment]
Works wel!
